# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest, windows-2019]
    steps:
      - uses: actions/checkout@v3

      - name: Setup linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update 
          sudo apt install pkg-config libudev-dev libusb-1.0-0-dev

      - uses: actions/setup-python@v4
        if: matrix.os != 'self-hosted-macos-arm'
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"

      - run: npm install -g prebuildify

      - run: npm run prepublishOnly
      - run: npm install
      - run: npm test
      
      - name: Make prebuilds
        run: prebuildify --napi

      - name: Make macOS arm64 prebuilds
        if: matrix.os == 'macos-latest'
        run: prebuildify --napi --arch arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.name}}-${{matrix.arch}}
          path: build/Release
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
